# See https://pre-commit.com for more information
# The configuration file for pre-commit hooks

# Ensure pre-commit is installed via:
# pip install pre-commit

# To install the hooks defined in this file, run:
# pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace  # Remove trailing whitespace
      - id: end-of-file-fixer  # Ensure files end with a newline
      - id: check-yaml  # Check YAML file syntax
      - id: check-added-large-files  # Prevent large files from being committed

  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest version of Black
    hooks:
      - id: black
        language_version: python3.9  # Set to the Python version you're using

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Use the latest stable version of Flake8
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]  # Align with Black's default line length
        additional_dependencies: ['flake8-bugbear', 'flake8-comprehensions']

#  - repo: https://github.com/pre-commit/mirrors-isort
#    rev: v5.12.0  # Use the latest version of isort
#    hooks:
#      - id: isort
#        name: Sort imports with isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991  # Use the latest version of mypy
    hooks:
      - id: mypy
        additional_dependencies: ['types-requests']  # Add necessary type stubs if needed

#  - repo: https://github.com/pre-commit/mirrors-bandit
#    rev: v1.7.5  # Security linter
#    hooks:
#      - id: bandit
#        args: ["--skip=B101"]  # Optionally skip certain checks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict  # Check for merge conflicts
