version: '3.7'

services:
    web:
        image: mlflow_server
        env_file: "all.env"
        restart: always
        build: ./mlflow
        container_name: mlflow_server
        ports:
            - "5000:5000"
        volumes:
            -   mlflow-data:/mlflow

volumes:
    mlflow-data:
    postgres-db-volume: